name: Publish Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build wheel twine setuptools
    - name: Build package
      run: python -m build
    - name: Publish package to GitHub Packages
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.GITHUB_TOKEN }}
        repository_url: https://maven.pkg.github.com/Husseinyehya1853/lantransfer
        skip_existing: true